version: "3"

services:
  web:
    image: ghcr.io/gcnyin/crypto-coins-market:0.1.0
    restart: always
    ports:
      - 9001:9000
    networks:
      - database
    depends_on:
      - postgres
    environment:
      - DB_JDBC_URL=jdbc:postgresql://postgres:5432/market
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678
      - JAVA_OPTS=${JAVA_OPTS}
  postgres:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - database
    environment:
      - POSTGRES_DB=market
      - POSTGRES_PASSWORD=12345678
  redis:
    image: redis:6.2.4-alpine3.13
    restart: always
    ports:
      - 6379:6379
    networks:
      - redis
networks:
  database:
  redis:
